export type Language = 'sq' | 'en' | 'sb';

const values = {
  sq: {
    Required: 'Obligative',
    Photo: 'Imazhi',
    'User Image': 'Imazhi',
    bag: 'Çantë/Thes',
    bottle: 'Shishe',
    can: 'Kanaçe',
    carton: 'Paketë',
    freezing: 'Ngrirje',
    division: 'Ndarje / Pastrim',
    drying: 'Tharje',
    pressing: 'Shtrydhje',
    grinding: 'Coptëzim',
    extraction: 'Ekstraktim',
    incision: 'Prerje',
    fermentation: 'Fermentim',
    filtering: 'Sitja',
    blending: 'Bluarje',
    Freezing: 'Ngrirje',
    Division: 'Ndarje / Pastrim',
    Drying: 'Tharje',
    Pressing: 'Shtrydhje',
    Grinding: 'Coptëzim',
    Extraction: 'Ekstraktim',
    Incision: 'Prerje',
    Fermentation: 'Fermentim',
    Filtering: 'Sitja',
    Blending: 'Bluarje',
    Farmers: 'Fermerit',
    Member: 'Antarit',
    'List of Zones': 'Ditari i Zonave',
    'List of Harvesters': 'Ditari i Vjelesve',
    'List of Processing Units': 'Ditari i Perpunimit te Njesive',
    'List of Cleanings': 'Ditari i Pastrimit',
    'List of Crops': 'Lista e Bimeve',
    'Previous Crop Code': 'Kodi i Mëhershëm i Bimës',
    'Modified Crop Code': 'Kodi i Ndryshuar i Bimës',
    'Parcel Ownership': 'Pronësia e Parcelës',
    jar: 'Kavanoz',
    jug: 'Enë',
    'Sub Parcel Code': 'Kodi i Nën parcelës',
    'Land Parcel Code': 'Kodi i Parcelës',
    'Land Parcel List': 'Lista e parcelave',
    'Drier Number': 'Numri i Tharëses',
    'Drier Temperature': 'Temperatura e Tharëses (℃)',
    'Drier Start Time': 'Fillimi Tharjes',
    'Drying Start Date': 'Data e Fillimit të Tharjes',
    'Drying End Date': 'Data e Mbarimit të Tharjes',
    'Drier End Time': 'Mbarimi Tharjes',
    pail: 'Kovë',
    Document: 'Dokumenti',
    'Analysis Document': 'Dokumenti i Analizes',
    not_applicable: 'Nuk është e aplikueshme',
    legal: 'Person Juridik',
    physical: 'Person Fizik',
    'Map Document': 'Dokumenti i Hartës',
    'Open Document': 'Hap Dokumentin',
    'List of Member Activities': 'Lista e aktiviteteve',
    'Should define crop status': 'Duhet cekur statusi i bimës',
    'Contract File': 'Dokumenti i Kontratës',
    Contract: 'Kontrata',
    'Cleaned Device': 'Pajisja e pastruar',
    'Product Type': 'Lloji i Produktit',
    processed: 'Përpunuar',
    'not processed': 'Pa Përpunuar',
    'Reason of Cleaning': 'Arsyeja e pastrimit',
    Members: 'Antarët',
    'Member Activities': 'Aktivitetet e Biznesit',
    'Legal Status': 'Statusi Legal',
    Legal: 'Person Juridik',
    Physical: 'Person Fizik',
    'Legal Person': 'Person Juridik',
    'Physical Person': 'Person Fizik',
    'External Id': 'Numri identifikues i Fermerit',
    'Open Image': 'Shiqo Imazhin',
    'Family Members': 'Antarët e Familjes',
    'Cadastral Number': 'Numri kadastral',
    'List of Land Parcels': 'Lista e Parcelave',
    'New Contracted Farmer': 'Shto Fermer te kontraktuar',
    Activities: 'Aktivitetet',
    'Owner Name': 'Emri Pronarit',
    'Owner Surname': 'Mbiemri Pronarit',
    'Owner First Name': 'Emri i Pronarit',
    'Owner Last Name': 'Mbiemri i Pronarit',
    'Applied Standards': 'Standardet e Aplikuara',
    'Organic Transition Date': 'Kalimi në kultivim organik',
    Farm: 'Fermës',
    Standard: 'Standardi',
    'Choose Document': 'Ngarko Dokumentin',
    'Planting Date': 'Data e mbjelljes',
    'Filter Data': 'Filtro të dhënat',
    Location: 'Lokacioni',
    Address: 'Adresa',
    'Number of Harvesters': 'Numri i vjelësve',
    'Ownership Status': 'Statusi i Pronësisë',
    'Type of Processing': 'Funksioni i Njësisë',
    'Total Area': 'Sipërfaqja Totale (ha)',
    'Total Area (sqm)': 'Sipërfaqja Totale (m2)',
    Area: 'Sipërfaqja (ha)',
    owned: 'Në Pronësi',
    rented: 'Me Qira',
    'Harvesting Time': 'Koha e vjeljes',
    'Planting Time': 'Koha e mbjelljes',
    'Buffer Zone': 'Zona tampon (ha)',
    'Utilised Area': 'Sipërfaqja e punuar (ha)',
    'Land Parcels': 'Parcelat',
    Zones: 'Zonat',
    Fraction: 'Fraksioni',
    Code: 'Kodi',
    'Zone Code': 'Kodi i Zonës',
    'First name': 'Emri',
    'Last name': 'Mbiemri',
    Supplier: 'Furnitori',
    'Product/Service': 'Produkti/Shërbimi',
    Price: 'Çmimi',
    Total: 'Totali',
    Customer: 'Klienti',
    'Harvesting Activities': 'Ditari i Vjeljes',
    'Collection Activities': 'Ditari i Grumbullimit',
    Collections: 'Grumbullimi',
    'Processing Units': 'Njesitë përpunuese',
    Processing: 'Përpunimi',
    Pesticides: 'Pesticidet',
    'Planting Materials': 'Materialet mbjellëse',
    'Contracted Farmers': 'Fermerët e Kontraktuar',
    Cultivation: 'Kultivimi',
    Stocks: 'Stoqet',
    'Farm Activities': 'Ditari i Punëve në Fermë',
    'Processing Activities': 'Ditari i Përpunimit',
    'Drying Activities': 'Ditari i Tharjes',
    Date: 'Data',
    Zone: 'Zona',
    Harvester: 'Vjelësi',
    'Admission Number': 'Nr. pranimit',
    Admission: 'Pranimi',
    Name: 'Emri',
    'Crop State': 'Gjendja e Bimës',
    'Crop Status': 'Statusi i Bimës',
    'Part Of Crop': 'Pjesa e Bimës',
    'Net Quantity': 'Sasia (neto) (kg)',
    'Gross Quantity': 'Sasia (bruto) (kg)',
    'Created At': 'Created At',
    'Land Parcel': 'Parcela',
    Crop: 'Bima',
    Crops: 'Bimët',
    Sales: 'Ditari i Shitjeve',
    Quantity: 'Sasia',
    'Activity Type': 'Lloji i aktivitetit',
    'Input Type': 'Lloji i Inputit',
    'Time Spent': 'Koha e shpenzuar',
    Comments: 'Komente',
    Dashboard: 'Dashboard',
    'Part of crop': 'Pjesa e bimës',
    'Crop state': 'Gjendja e bimës',
    Dry: 'Tharë',
    Fresh: 'Freskët',
    'Crop status': 'Statusi i Bimës',
    Organic: 'Organik',
    organic: 'Organik',
    conventional: 'Konvencional',
    'Gross Weight': 'Pesha (bruto)',
    Weight: 'Pesha',
    'Net Weight': 'Pesha (neto)',
    Notes: 'Shënime',
    'List of crops': 'Lista e bimëve',
    'Gross quantity': 'Sasia (bruto)',
    'Net quantity': 'Sasia (neto)',
    'Activity Category': 'Lloji i aktivitetit',
    'Organic Category': 'Inputi Organik',
    Activity: 'Aktiviteti',
    'Organic Type': 'Inputi Organik',
    Collection: 'Grumbullim',
    Harvesting: 'Kultivim',
    'Admission no.': 'Nr. pranimit',
    'Purchase Admissions': 'Ditari i Pranimeve te Produkteve',
    'Admissions List': 'Ditari i Pranimeve',
    'Part of Crop': 'Pjesa e bimës',
    Firo: 'Firo',
    'Processing Method': 'Mënyra e përpunimit',
    'Lot Code': 'Kodi Final',
    'Zone/Land Parcel': 'Zona/Parcela',
    Longitude: 'Gjatësia gjeografike',
    Latitude: 'Gjerësia gjeografike',
    'Contract End Date': 'Mbarimi i Kontrates',
    'Contract Start Date': 'Fillimi i Kontrates',
    soil_analysis: 'Analiza e Tokës',
    'Soil Analysis Activities': 'Ditari i Analizave të Tokës',
    land_preparation: 'Pergaditja e Tokës',
    land_ploughing: 'Lëvrimi',
    'Land Ploughing Activities': 'Ditari i Lëvrimit',
    milling: 'Frezimi',
    'Milling Activities': 'Ditari i Frezimit',
    bed_preparation: 'Përgatitja e shtratit',
    'Bed Preparation Activities': 'Ditari i Përgatitjes se shtratit',
    fertilization: 'Plehërimi',
    'Fertilization Activities': 'Ditari i Plehërimit',
    seed_planting: 'Mbjellja e bimës',
    'Seed Planting Activities': 'Ditari i Mbjelljes se Bimëve',
    crop_protection: 'Mbrojtja',
    'Crop Protection Activities': 'Ditari i Mbrojtjes se Bimëve',
    grazing_management: 'Menaxhimi i barojave',
    'Grazing Management Activities': 'Ditari i Menaxhimit te barojave',
    irrigation: 'Ujitja',
    'Irrigation Activities': 'Ditari i Ujitjes',
    harvesting: 'Vjelja',
    'pH Level': 'pH i dheut',
    'N Level': 'N (kg/ha)',
    'P Level': 'P (kg/ha)',
    'K Level': 'K (kg/ha)',
    Depth: 'Thellësia e lëvrimit (cm)',
    Devices: 'Paisjet e përdorura',
    'Fuel Used': 'Sasia e shpenzuar e karburantit (L)',
    Cost: 'Shërbimi i paguar (€)',
    Type: 'Lloji',
    Origin: 'Origjina',
    inorganic: 'Jo Organik',
    'Sub type': 'Nën lloji',
    plant_origin: 'Origjina bimore (Plehu i gjelbër)',
    animal_origin: 'Origjina shtazore (Plehu i shtallës)',
    compost: 'Kompost',
    nitrogen_based: 'Plehra azotike',
    phosphoric: 'Plehra fosforike',
    potassic: 'Plehra kaliumi',
    micronutrients: 'Plehra e mikronutrientëve',
    superphosphate: 'Superfosfat',
    ammonium_nitrate: 'Nitratet e amonit',
    potassium_sulphate: 'Sulfati i kaliumit',
    Producer: 'Prodhuesi',
    'Applied Quantity': 'Sasia e Aplikuar (kg)',
    'Remaining Quantity': 'Sasia e mbetur (kg)',
    'Nitrogen Quantity': 'Sasia e Nitrogjenit (kg)',
    Product: 'Produkti',
    SKU: 'SKU',
    Hours: 'Orë',
    Minutes: 'Minuta',
    'Material Type': 'Lloji i Materialit',
    'Material Origin': 'Origjina',
    Status: 'Statusi',
    Distance: 'Distanca (cm)',
    seed: 'Farë',
    seedling: 'Fidane',
    cutting: 'Copëza',
    root: 'Rrënjë',
    own: 'Vetanake',
    purchased: 'Blerë',
    untreated_conventional: 'Konvencional i patrajtuar',
    manual: 'Manual',
    mechanical: 'Mekanike',
    Persons: 'Nr. personave',
    Disease: 'Sëmundja ose dēmtuesi i synuar',
    'Copper Quantity': 'Sasia e Bakrit',
    drip: 'Sistemi i ujitjes pikë - pikë',
    sprinkler: 'Sistemi i sprinkler',
    day: 'Në ditë',
    week: 'Në javë',
    month: 'Në muaj',
    'Personal Number': 'Numri Personal',
    'Irrigation Method': 'Metoda e ujitjes',
    'Frequency Unit': 'Shpeshtësia',
    Frequency: 'Frekuenca',
    'Harvesting Quantity': 'Sasia e vjeljes',
    'Packaging Type': 'Lloji i paketimit',
    'Packaging Type / Transport Type':
      'Lloji i paketimiti / Mjeti i transportit',
    sack: 'Qese',
    box: 'Kuti',
    crate: 'Kuti e madhe',
    'Storage Unit': 'Njësia deponuese',
    Admissions: 'Pranimi',
    'Admissions from Farmers': 'Pranimet e produkteve',
    k1: 'K1',
    k2: 'K2',
    k3: 'K3',
    dry: 'Tharë',
    fresh: 'Freskët',
    'Contracted Farmer': 'Fermeri i kontraktuar',
    Farmer: 'Fermeri',
    Subject: 'Subjekti',
    Purchase: 'Blerje',
    'Zone / Parcel': 'Zona / Parcela',
    'Processing Unit': 'Njësia përpunuese',
    'Processing Type': 'Makineria e perdorur',
    Inventory: 'Stoku',
    'Inventory Locations': 'Ditari i Magazinimit',
    'Area (sqm)': 'Sipërfaqja (m2)',
    Locations: 'Lokacionet',
    fertilization_machine: 'Makinë e plehërimit',
    seed_planting_machine: 'Makinë e mbjelljes',
    grazing_machine: 'Makinë e barojave',
    ploughing_machine: 'Makinë e lëvrimit',
    harvesting_machine: 'Makinë e vjeljes',
    'Harvesting Inventory': 'Produktet e kultivuara',
    'Collection Inventory': 'Produktet e grumbulluara',
    'Processing Inventory': 'Lista e produkteve finale',
    'Cleaning Area': 'Hapësira e pastruar',
    'Cleaning Tool': 'Mjeti i pastrimit',
    'New Activity': 'Aktivitet i ri',
    'Responsible Person': 'Personi përgjegjës',
    'Duration of the rental contract': 'Kohëzgjatja e kontratës së qirasë',
    'last year': 'viti i kaluar',
    Inputs: 'Inputet',
    'Product Name': 'Emri dhe brendi i produktit',
    'Product Description': 'Përshkrimi i produktit',
    'Package Type': 'Lloji i paketimit',
    'Purchase Date': 'Data e blerjes',
    'Expiry Date': 'Data e skadimit',
    'New Item': 'Artikull i ri',
    'Sale Type': 'Lloji i shitjes',
    product: 'Produkt',
    service: 'Shërbim',
    planned: 'planifikuar',
    'Inventory Item': 'Artikulli i stokut',
    collected_product: 'Grumbullim',
    harvested_product: 'Kultivim',
    purchased_product: 'Blerje',
    processed_product: 'Përpunim',
    plating_material: 'Materiale mbjellëse',
    input: 'Input',
    Description: 'Përshkrimi',
    Users: 'Menaxho Shfrytëzuesit',
    'Sub Parcels': 'Nën parcelat',
    Parcelization: 'Parcelizimi',
    'Crop Turnover': 'Qarkullimi bimor',
    map: 'Lokacioni',
    parcelization: 'Parcelizimi',
    crop_turnover: 'Qarkullimi bimor',
    'Sub Parcel': 'Nën Parcela',
    Source: 'Burimi',
    well: 'Bunar',
    river: 'Lumi',
    public_systems: 'Sistemet publike',
    'Active Ingredient': 'Substanca Aktive',
  },
  en: {},
  sr: {
    Required: 'Obavezno',
    Photo: 'Fotografija',
    bag: 'Vreća',
    bottle: 'Flaša',
    can: 'Konzerva',
    OR: 'OP',
    Register: 'Registrovati',
    carton: 'Kutija',
    freezing: 'Zamrzavanje',
    division: 'Podela',
    drying: 'Sušenje',
    pressing: 'Presovanje',
    grinding: 'Mlevenje',
    extraction: 'Ekstrakcija',
    Freezing: 'Zamrzavanje',
    'Sign up': 'Prijavi se',
    'Create Acount': 'Registruj se',
    Division: 'Podela',
    Drying: 'Sušenje',
    Pressing: 'Presovanje',
    'New Data': 'Prihvati',
    Grinding: 'Mlevenje',
    Extraction: 'Ekstrakcija',
    jar: 'Tegla',
    jug: 'Vrč',
    'Dried Product': 'Sušeni proizvod',
    'Purchased Product': 'Kupljeni proizvod',
    'Harvested Product': 'Ubreni proizvod',
    'Collected Product': 'Sakupljeni proizvod',
    dried_product: 'Sušeni proizvod',
    purchased_product: 'Kupljeni proizvod',
    harvested_product: 'Ubreni proizvod',
    collected_product: 'Sakupljeni proizvod',
    'Sub Parcel Code': 'Kod podparcele',
    'Land Parcel Code': 'Kod parcele',
    'Drier Number': 'Broj sušare',
    'Drier Temperature': 'Temperatura sušare (℃)',
    'Drier Start Time': 'Početak sušenja',
    'Drying Start Date': 'Datum početka sušenja',
    'Drying End Date': 'Datum završetka sušenja',
    'Drier End Time': 'Kraj sušenja',
    pail: 'Kofa',
    'Crop Name': 'Izreži ime',
    'Previous Crop Code': 'Prethodni kod useva',
    'Modified Crop Code': 'Izmenjeni biljni kodeks',
    'Crop (PPJD)': 'biljka (PPJD)',
    'Crop (BMA)': 'biljka (BMA)',
    'Crops (PPJD)': 'Kulture (PPJD)',
    'Crops (BMA)': 'Kulture (BMA)',
    'Crop Parts (PPJD)': 'Delovi kultura (PPJD)',
    'Crop Parts (BMA)': 'Delovi kultura (BMA)',
    'Crops Diseases': 'Crops Diseases',
    'Cultivation Activities': 'Aktivnosti uzgoja',
    'Processing Methods': 'Metode prerade',
    'Processing Types': 'Vrste prerade',
    Document: 'Dokument',
    'Analysis Document': 'Dokument analize',
    all_items: 'Svi predmeti',
    not_applicable: 'Neprimenljivo',
    cancel: 'Otkaži',
    legal: 'Pravno lice',
    physical: 'Fizičko lice',
    'Map Document': 'Dokument mape',
    'List of Member Activities': 'Lista aktivnosti članova',
    'Contract File': 'Fajl ugovora',
    Contract: 'Ugovor',
    'Cleaned Device': 'Očišćeni uređaj',
    'Product Type': 'Tip proizvoda',
    processed: 'Obrađen',
    not_processed: 'Neobrađen',
    'Reason of Cleaning': 'Razlog čišćenja',
    Members: 'Članovi',
    'Member Activities': 'Aktivnosti članova',
    'Legal Status': 'Pravni status',
    Legal: 'Pravno lice',
    Physical: 'Fizičko lice',
    'Legal Person': 'Pravno lice',
    'Physical Person': 'Fizičko lice',
    'Individual Business': 'Individualno preduzeće (I.P)',
    LLC: 'DOO (Društvo sa ograničenom odgovornošću)',
    'Agricultural Cooperative': 'Zemljoradnička zadruga',
    'External Id': 'identifikacioni broj farme',
    'Family Members': 'Članovi porodice',
    'Parcel is required': 'Parcela je potrebna',
    'Activity is required': 'Aktivnost je potrebna',
    'Cadastral Number': 'Katastarski broj',
    Remove: 'Ukloni',
    'List of Land Parcels': 'Lista parcela',
    Activities: 'Aktivnosti',
    'Applied Standards': 'Primеnjeni standardi',
    'Organic Transition Date': 'Datum prelaska na organsku poljoprivredu',
    'Personal Number': 'Personalni broj',
    Farm: 'Farma',
    'Planting Date': 'Datum sadnje',
    Owned: 'U vlasništvu',
    Location: 'Lokacija',
    Address: 'Adresa',
    'Number of Harvesters': 'Broj beraca',
    Harvesters: 'Beraci',
    Rented: 'Iznajmljeno',
    'Ownership Status': 'Status vlasništva',
    'Type of Processing': 'Vrsta prerade',
    'Total Area': 'Ukupna površina (ha)',
    'Total Area (sqm)': 'Ukupna površina (m2)',
    'Sub Parcel Area': 'Površina podparcele (ha)',
    Storage: 'Skladištenje',
    Area: 'Površina (ha)',
    'Area (sqm)': 'Površina (m2)',
    owned: 'U vlasništvu',
    rented: 'Iznajmljeno',
    'Buffer Zone': 'Tampon zona',
    'Utilised Area': 'Iskorišćena površina (ha)',
    'Land Parcels': 'Parcele',
    'Parcel Ownership': 'Vlasništvo parcele',
    Zones: 'Zone',
    Fraction: 'Frakсija',
    Code: 'Kod',
    'Zone Code': 'Kod zone',
    'First name': 'Ime',
    'Last name': 'Prezime',
    Sales: 'Prodaja',
    Expenses: 'Troškovi',
    'Dried Inventory': 'Spisak sušenih proizvoda',
    Supplier: 'Dobavljač',
    'Product/Service': 'Proizvod/Usluga',
    Price: 'Cena',
    Total: 'Ukupno',
    Customer: 'Klijent',
    'Harvesting Activities': 'Dnevnik berbe',
    'Collection Activities': 'Dnevnik prikupljanja',
    Collections: 'Prikupljanje',
    'Processing Units': 'Jedinice za preradu',
    Processing: 'Prerada',
    Pesticides: 'Pesticidi',
    'Planting Materials': 'Sadni material',
    'Contracted Farmers': 'Ugovoreni poljoprivrednici',
    Farmers: 'Poljoprivrednici',
    Member: 'Član',
    Cultivation: 'Uzgoj',
    Stocks: 'Zalihe',
    'Farm Activities': 'Aktivnosti na farmi',
    'Processing Activities': 'Aktivnosti Prerade',
    'Drying Activities': 'Aktivnosti sušenja',
    Date: 'Datum',
    Zone: 'Zona',
    Harvester: 'Berač',
    'Admission Number': 'Broj prijema',
    Admission: 'Prijem',
    Name: 'Ime',
    'Crop State': 'Stanje biljaka',
    'Crop Status': 'Status biljaka',
    'Part Of Crop': 'Deo biljke',
    'Net Quantity': 'Neto količina (kg)',
    'Gross Quantity': 'Bruto količina (kg)',
    'Created At': 'Stvorio se u',
    'Land Parcel': 'Parcela',
    Crop: 'Biljka',
    Crops: 'Biljke',
    Quantity: 'Količina',
    'Activity Type': 'Vrsta aktivnosti',
    'Input Type': 'Vrsta repromateriala',
    'Time Spent': 'Vreme provedeno',
    Comments: 'Komentari',
    'Part of crop': 'Deo biljke',
    Dry: 'Suv',
    Fresh: 'Svež',
    Organic: 'Organski',
    organic: 'Organski',
    Conventional: 'Konvencionalan',
    conventional: 'Konvencionalan',
    'Gross Weight': 'Bruto težina (kg)',
    Weight: 'Težina (kg)',
    'Net Weight': 'Neto težina (kg)',
    Notes: 'Beleške',
    'List of crops': 'Spisak biljaka',
    'Gross quantity': 'Bruto količina',
    'Activity Category': 'Vrsta aktivnosti',
    'Organic Category': 'Organska kategorija',
    Activity: 'Aktivnost',
    'Organic Type': 'Vrsta organskog repromateriala',
    Collection: 'Prikupljanje',
    collection: 'Prikupljanje',
    purchase: 'Uzgoj',
    Harvesting: 'Berba',
    'Admission no': 'Broj prijema',
    'Admission No': 'Broj prijema',
    'Admission no.': 'Broj prijema',
    'Part of Crop': 'Deo biljke',
    Firo: 'Gubitak',
    'Processing Method': 'Metoda prerade',
    'Lot Code': 'Kod serije',
    Years: 'Godine',
    'Crop List': 'Spisak biljaka',
    'Show Years & Months': 'Prikaži godine i meseci',
    'Save Changes': 'Sačuvaj promene',
    'Zone/Land Parcel': 'Zona/Parcela',
    Longitude: 'Geografska dužina',
    Latitude: 'Geografska širina',
    'New Storage': 'Novo skladište',
    'Contract End Date': 'Datum završetka ugovora',
    'Contract Start Date': 'Datum početka ugovora',
    'The sum of all crops area has surpassed the utilised area':
      'Ukupna površina useva premašila je iskorišćenu površinu',
    soil_analysis: 'Analiza zemljišta',
    land_preparation: 'Priprema zemljišta',
    land_ploughing: 'Oranje',
    milling: 'Freziranje zemljista',
    bed_preparation: 'Priprema ležišta',
    fertilization: 'Đubrenje',
    seed_planting: 'Sadnja semena',
    crop_protection: 'Zaštita biljaka',
    grazing_management: 'Upravljanje korovom',
    irrigation: 'Navodnjavanje',
    harvesting: 'Berba',
    'pH Level': 'pH zemljišta',
    'N Level': 'N  (kg/ha)',
    'Permitted N Level': 'Dozvoljeni nivo N (kg/ha/god)',
    'P Level': 'P (kg/ha)',
    'Permitted P Level': 'Dozvoljeni nivo P (kg/ha/god)',
    'K Level': 'K (kg/ha)',
    'Permitted K Level': 'Dozvoljeni nivo K (kg/ha/god)',
    Depth: 'Dubina oranja (cm)',
    Devices: 'Uređaji koji se koriste',
    'Fuel Used': 'Količina potrošenog goriva (L)',
    Cost: 'Trošak (€)',
    Type: 'Vrsta',
    Origin: 'Poreklo',
    inorganic: 'Neorganski',
    'Sub type': 'Podvrsta',
    plant_origin: 'Biljnog porekla (zeleno đubrivo)',
    animal_origin: 'Životinjskog porekla (stajsko đubrivo)',
    compost: 'Kompost',
    nitrogen_based: 'Azotna đubriva',
    phosphoric: 'Fosforna đubriva',
    potassic: 'Kalijumova đubriva',
    micronutrients: 'Mikronutrijenti',
    superphosphate: 'Superfosfat',
    ammonium_nitrate: 'Amonijum nitrat',
    potassium_sulphate: 'Kalijum sulfat',
    Producer: 'Proizvođač',
    'Applied Quantity': 'Primеnjеna količina (kg)',
    'Remaining Quantity': 'Preostala količina (kg)',
    'Nitrogen Quantity': 'Količina azota (kg)',
    Product: 'Proizvod',
    Hours: 'Sati',
    'At Hour': 'U sati',
    Minutes: 'Minuti',
    'Material Type': 'Vrsta materijala',
    'Material Origin': 'Poreklo',
    Status: 'Status',
    Distance: 'Rastojanje (cm)',
    seed: 'Seme',
    seedling: 'Rasad',
    cutting: 'Rezanci',
    root: 'Koren',
    own: 'Sopstveno',
    purchased: 'Kupljeno',
    untreated_conventional: 'Neobrađeno konvencionalno',
    manual: 'Ručno',
    mechanical: 'Mehanički',
    Persons: 'Broj osoba',
    Disease: 'Bolest ili ciljani štetočin',
    'Copper Quantity': 'Količina bakra',
    drip: 'Sistem za kap po kap',
    sprinkler: 'Prskalica',
    day: 'Dan',
    week: 'Nedelja',
    month: 'Mesec',
    'Irrigation Method': 'Metoda navodnjavanja',
    'Frequency Unit': 'Jedinica frekvencije',
    Frequency: 'Frekvencija',
    'Harvesting Quantity': 'Količina berbe',
    'Packaging Type': 'Vrsta pakovanja',
    'Packaging Type / Transport Type': 'Vrsta pakovanja / Vrsta transporta',
    sack: 'Vreća',
    box: 'Kutija',
    crate: 'Velika kutija',
    'Storage Unit': 'Deponovana jedinica',
    Admissions: 'Prijemi',
    'Admissions from Farmers': 'Prijemi od poljoprivrednika',
    k1: 'K1',
    k2: 'K2',
    k3: 'K3',
    dry: 'Suv',
    fresh: 'Svež',
    'Contracted Farmer': 'Ugovoreni poljoprivrednik',
    Farmer: 'Poljoprivrednik',
    Subject: 'Subjekat',
    Purchase: 'Kupovina',
    'Zone / Parcel': 'Zona / Parcela',
    'Processing Unit': 'Jedinica za preradu',
    'Processing Type': 'Vrsta prerade',
    approved: 'Odobreno',
    declined: 'Odbio',
    pending: 'Nerešen',
    'Date of Approval': 'Datum odobrenja',
    'Approval Status': 'Stanje odluke o odobrenju',
    Inventory: 'Zalihe',
    Locations: 'Lokacije',
    fertilization_machine: 'Mašina za gnojidbu',
    seed_planting_machine: 'Mašina za sadnju',
    grazing_machine: 'Mašina za korove',
    ploughing_machine: 'Mašina za oranje',
    harvesting_machine: 'Mašina za berbu',
    'Harvesting Inventory': 'Inventar berbe',
    'Collection Inventory': 'Inventar prikupljanja',
    'Processing Inventory': 'Inventar obrade',
    'Cleaning Area': 'Očišćeni prostor',
    'Cleaning Tool': 'Alat za čišćenje',
    'Responsible Person': 'Odgovorna osoba',
    Inputs: 'Ulazi',
    'Product Name': 'Naziv i marka proizvoda',
    'Product Description': 'Opis proizvoda',
    'Package Type': 'Vrsta pakovanja',
    'Purchase Date': 'Datum kupovine',
    'Expiry Date': 'Datum isteka',
    'Sale Type': 'Vrsta prodaje',
    product: 'Proizvod',
    service: 'Usluga',
    'Inventory Item': 'Stavka inventara',
    processed_product: 'Prerađeni proizvod',
    planting_material: 'Materijal za sadnju',
    input: 'Repromaterial ',
    Description: 'Opis',
    Users: 'Upravljaj korisnicima',
    'Sub Parcels': 'Podparcele',
    'Sub parcels are the smaller parcels within the main parcel':
      'Podparcele su manje parcele unutar glavne parcele',
    'Add Sub Parcel': 'Dodaj podparcelu',
    Parcelization: 'Parcelacija',
    'Crop Turnover': 'Promet useva',
    map: 'Mapa',
    parcelization: 'Parcelacija',
    crop_turnover: 'Promet useva',
    'Sub Parcel': 'Podparcela',
    'Crop Order': 'Redosled useva',
    Source: 'Izvor',
    well: 'Bunar',
    river: 'Reka',
    public_systems: 'Javni sistemi',
    'Active Ingredient': 'Aktivni sastojak',
    Accounting: 'Računovodstvo',
    expenses_other: 'Ostali troškovi',
    expenses_land_ploughing: 'Troškovi oranja',
    expenses_milling: 'Troškovi freziranja',
    expenses_bed_preparation: 'Troškovi pripreme ležišta',
  },
};

export function translation(lang: Language) {
  const locale = values[lang];

  function t(arg?: string) {
    if (!arg) return '';

    if (locale[arg]) return locale[arg];
    else return arg;
  }

  return { t };
}
